CREATE TABLE IF NOT EXISTS app_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '应用 ID',
    app_name VARCHAR(100) NOT NULL COMMENT '应用名称',
    package_name VARCHAR(128) NOT NULL COMMENT '包名或 Bundle ID',
    app_type TINYINT NOT NULL DEFAULT 1 COMMENT '1=Android 2=iOS',
    app_description VARCHAR(512) DEFAULT NULL COMMENT '应用描述',
    copyright_no VARCHAR(100) DEFAULT NULL COMMENT '软件著作权登记号',
    icp_no VARCHAR(100) DEFAULT NULL COMMENT 'ICP 备案号',
    app_record_no VARCHAR(100) DEFAULT NULL COMMENT '应用备案号',
    privacy_url VARCHAR(255) DEFAULT NULL COMMENT '隐私政策地址',
    user_agreement_url VARCHAR(255) DEFAULT NULL COMMENT '用户协议地址',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '0=禁用 1=启用',
    create_user VARCHAR(255) DEFAULT NULL COMMENT '创建人',
    update_user VARCHAR(255) DEFAULT NULL COMMENT '更新人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_app_info_package_name (package_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用基础信息表';

CREATE TABLE IF NOT EXISTS app_store_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键 ID',
    store_type VARCHAR(20) NOT NULL COMMENT '应用商店类型',
    account_name VARCHAR(255) DEFAULT NULL COMMENT '账号名称',
    email VARCHAR(255) DEFAULT NULL COMMENT '邮箱',
    phone VARCHAR(255) DEFAULT NULL COMMENT '手机号',
    client_id VARCHAR(255) DEFAULT NULL COMMENT '客户端 ID 或 API Key',
    client_secret VARCHAR(255) DEFAULT NULL COMMENT '客户端密钥或 API Secret',
    public_key TEXT DEFAULT NULL COMMENT '公钥',
    private_key VARCHAR(255) DEFAULT NULL COMMENT '私钥',
    token VARCHAR(500) DEFAULT NULL COMMENT '静态 Token',
    ip_whitelist VARCHAR(500) DEFAULT NULL COMMENT 'IP 白名单',
    privacy_url VARCHAR(255) DEFAULT NULL COMMENT '隐私政策地址',
    icon LONGTEXT DEFAULT NULL COMMENT '图标 Base64',
    app_id VARCHAR(100) DEFAULT NULL COMMENT '应用商店侧 appId 或 contentId',
    api_status TINYINT NOT NULL DEFAULT 1 COMMENT '0=禁用 1=启用',
    create_user VARCHAR(255) DEFAULT NULL COMMENT '创建人',
    update_user VARCHAR(255) DEFAULT NULL COMMENT '更新人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_store_config_store_type (store_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用商店账号配置表';

CREATE TABLE IF NOT EXISTS app_version (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '版本 ID',
    app_id BIGINT NOT NULL COMMENT '应用 ID',
    version_name VARCHAR(30) NOT NULL COMMENT '版本名称',
    version_code VARCHAR(64) NOT NULL COMMENT '版本号',
    package_url_32 VARCHAR(255) DEFAULT NULL COMMENT '32 位安装包路径',
    package_url_64 VARCHAR(255) DEFAULT NULL COMMENT '64 位安装包路径',
    package_app_url VARCHAR(255) DEFAULT NULL COMMENT '鸿蒙安装包路径',
    build_code VARCHAR(64) DEFAULT NULL COMMENT '构建号',
    update_log TEXT COMMENT '更新说明',
    is_reinforce TINYINT NOT NULL DEFAULT 0 COMMENT '0=未加固 1=已加固',
    create_user VARCHAR(255) DEFAULT NULL COMMENT '创建人',
    update_user VARCHAR(255) DEFAULT NULL COMMENT '更新人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UNIQUE KEY uk_app_version_unique (app_id, version_name, version_code),
    KEY idx_app_version_app (app_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用版本表';

CREATE TABLE IF NOT EXISTS app_release_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '发布记录 ID',
    app_id BIGINT NOT NULL COMMENT '应用 ID',
    version_id BIGINT NOT NULL COMMENT '版本 ID',
    store_type VARCHAR(20) NOT NULL COMMENT '应用商店类型',
    release_mode VARCHAR(20) NOT NULL DEFAULT 'api' COMMENT '发布模式',
    release_type BIGINT NOT NULL DEFAULT 1 COMMENT '1=全量 2=灰度',
    gray_percent BIGINT DEFAULT NULL COMMENT '灰度比例',
    gray_start_time DATETIME DEFAULT NULL COMMENT '灰度开始时间',
    gray_end_time DATETIME DEFAULT NULL COMMENT '灰度结束时间',
    auto_full BIGINT NOT NULL DEFAULT 1 COMMENT '是否自动转全量',
    release_status VARCHAR(20) NOT NULL DEFAULT 'draft' COMMENT '发布状态',
    store_release_id VARCHAR(100) DEFAULT NULL COMMENT '商店侧发布单 ID',
    reject_reason TEXT COMMENT '驳回原因',
    api_request_log TEXT COMMENT 'API 请求日志',
    api_response_log TEXT COMMENT 'API 响应日志',
    release_time DATETIME DEFAULT NULL COMMENT '提交时间',
    finish_time DATETIME DEFAULT NULL COMMENT '完成时间',
    create_user VARCHAR(255) DEFAULT NULL COMMENT '创建人',
    update_user VARCHAR(255) DEFAULT NULL COMMENT '更新人',
    KEY idx_release_record_app (app_id),
    KEY idx_release_record_version (version_id),
    KEY idx_release_status_store (release_status, store_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用发布记录表';

CREATE TABLE IF NOT EXISTS app_api_token_cache (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键 ID',
    store_config_id BIGINT NOT NULL COMMENT '商店配置 ID',
    token_type VARCHAR(20) NOT NULL COMMENT 'Token 类型',
    token_value TEXT COMMENT 'Token 值',
    expire_time DATETIME DEFAULT NULL COMMENT '过期时间',
    create_user VARCHAR(255) DEFAULT NULL COMMENT '创建人',
    update_user VARCHAR(255) DEFAULT NULL COMMENT '更新人',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_token_cache_store_type (store_config_id, token_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Token 缓存表';

CREATE TABLE IF NOT EXISTS app_store_request_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '商店请求日志 ID',
    release_record_id BIGINT DEFAULT NULL COMMENT '发布记录 ID',
    store_config_id BIGINT NOT NULL COMMENT '商店配置 ID',
    store_type VARCHAR(20) NOT NULL COMMENT '应用商店类型',
    action VARCHAR(100) NOT NULL COMMENT '操作动作',
    request_order BIGINT DEFAULT NULL COMMENT '同一次发布内的请求顺序',
    request_method VARCHAR(10) NOT NULL COMMENT 'HTTP 方法',
    request_url VARCHAR(500) NOT NULL COMMENT '请求地址',
    request_params TEXT COMMENT '请求参数',
    request_body LONGTEXT COMMENT '请求体',
    response_status_code INT DEFAULT NULL COMMENT '响应状态码',
    response_body LONGTEXT COMMENT '响应体',
    request_status VARCHAR(20) NOT NULL COMMENT '请求状态',
    error_message VARCHAR(1000) DEFAULT NULL COMMENT '错误信息',
    duration_ms BIGINT DEFAULT NULL COMMENT '耗时（毫秒）',
    create_user VARCHAR(255) DEFAULT NULL COMMENT '创建人',
    update_user VARCHAR(255) DEFAULT NULL COMMENT '更新人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    KEY idx_store_request_log_release_order (release_record_id, request_order),
    KEY idx_store_request_log_store_type_time (store_type, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用商店请求日志表';
